set(TEST_GIT_REPO "https://github.com/libcellml/tutorials")
set(TEST_COMMIT_HASH "bbbf1ee")

set(TEST_TARGETS 
  tutorial1_complete
  tutorial2_complete
  tutorial3_complete
  tutorial4_complete
  tutorial5_complete
  createGateModel_complete
  createPotassiumChannelModel_complete
  debugSodiumChannelModel_complete
  generateMembraneModel_complete
  solveGeneratedCode_complete
)
set(PYTEST_TARGETS
  tutorial1/tutorial1_complete.py
  tutorial2/tutorial2_complete.py
  tutorial3/tutorial3_complete.py
  tutorial4/tutorial4_complete.py
  tutorial5/tutorial5_complete.py
  hh_tutorial1/createGateModel_complete.py
  hh_tutorial2/createPotassiumChannelModel_complete.py
  hh_tutorial3/debugSodiumChannelModel_complete.py
  hh_tutorial4/generateMembraneModel_complete.py
  hh_tutorial5/solveGeneratedCode_complete.py
)
set(PYTEST_TARGETS_ENV
  "PYTHONPATH=@TEST_ROOT@/utilities/"
)
set(TEST_TARGETS_ARGS
  tutorial1/tutorial1.cellml
  tutorial2/tutorial2.cellml
  "NOTFOUND"
  "NOTFOUND"
  tutorial5/MysteryModel.cellml
  "NOTFOUND"
  hh_tutorial2/
  hh_tutorial3/SodiumChannelModel_broken.cellml
  hh_tutorial4/MembraneModel.cellml
  "NOTFOUND"
)
set(PYTEST_TARGETS_ARGS ${TEST_TARGETS_ARGS})
set(TEST_CMAKELISTS_DIR
  tutorial1
  tutorial2
  tutorial3
  tutorial4
  tutorial5
  hh_tutorial1
  hh_tutorial2
  hh_tutorial3
  hh_tutorial4
  hh_tutorial5
)
set(TEST_EXPECTED_RESULTS
  tutorial1/expected_results/
  tutorial2/expected_results/
  tutorial3/expected_results/
  tutorial4/expected_results/
  tutorial5/expected_results/
  hh_tutorial1/expected_results/
  hh_tutorial2/expected_results/
  hh_tutorial3/expected_results/
  hh_tutorial4/expected_results/
  hh_tutorial5/expected_results/
)
set(PYTEST_EXPECTED_RESULTS ${TEST_EXPECTED_RESULTS})

